default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sweet_development

test:
  <<: *default
  database: sweet_test

production:
  <<: *default
  database: sweet_production
  username: sweet
  password: <%= ENV['SWEET_DATABASE_PASSWORD'] %>
